packages:
  - '.'
allowBuilds:
  '@hugeicons/svelte': false
  '@tailwindcss/oxide': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@sveltejs/adapter-node@6.0.0'
  - '@sveltejs/kit@3.0.0'

overrides:
  '@esbuild-kit/core-utils>esbuild': ^0.28.1
